### ISSUE TITLE
ipv4_address only exposes a single interface, tends to change to an unreachable address if one is configured

### ISSUE THREAD

**Issue by lathiat** [terraform-lxd/terraform-provider-lxd#453] opened 2024-04-10 06:05 UTC
Currently lxd_instance.name.ipv4_address only exposes a single address/interface. If you have multiple interfaces configured, the value may switch to an different or private/inaccessible IP address.

There is currently no way to pick one of the others, even manually.

### Specific use case
I am using terraform to deploy LXD VMs, exporting the instances as ansible inventory and then using ansible to configure them. As part of that, I install libvirt-daemon to deploy VMs inside the VM (in this case to test a libvirt issue).

Once you install libvirt-daemon, it creates and sets up a virtual bridge (virbr0) with the IP 192.168.122.1 (which is not routable from outside the VM).

Next time I re-run terraform it always switches the ipv4_address from the previously good public IP (enp5s0/172.16.0.*) to the private IP (virbr0/192.168.122.1).

This means ansible can no longer connect and configure the instance, even though it worked at the start.

It is notable that in my case I am using an unmanaged network for the instance, with a 'type: bridged' NIC and LXD is not performing IPAM. I am also currently using VMs. I have not tested the behaviour with containers or when LXD is doing IPAM. The IPs are reported back by the LXD agent inside the VM.

### Proposed Resolution
Ideally, LXD would know which interface had the default route, and pick that as a preference.

It doesn't currently seem to expose that in the API, ideally it could, but in the absence of that, exposing all of the IP addresses would at least allow someone to pick one by interface name. It's not ideal as that interface name can change depending on the workload, but would at least give a workable option for this use case.

`lxc ls` exposes the full list:
```
$ lxc ls
+------+---------+------------------------+------+-----------------+-----------+
| NAME |  STATE  |          IPV4          | IPV6 |      TYPE       | SNAPSHOTS |
+------+---------+------------------------+------+-----------------+-----------+
| vm1  | RUNNING | 192.168.122.1 (virbr0) |      | VIRTUAL-MACHINE | 0         |
|      |         | 172.16.0.206 (enp5s0)  |      |                 |           |
+------+---------+------------------------+------+-----------------+-----------+
| vm2  | RUNNING | 193.1.1.1 (z-test)     |      | VIRTUAL-MACHINE | 0         |
|      |         | 192.168.122.1 (virbr0) |      |                 |           |
|      |         | 173.168.200.1 (a-test) |      |                 |           |
|      |         | 172.16.0.207 (enp5s0)  |      |                 |           |
+------+---------+------------------------+------+-----------------+-----------+
```

`lxc ls` seems to be ordering the list alphabetically by IP address, so the order is predictable but which interface you get will be dependant on what subnet and IP address you are using for the different interfaces.

terraform seems to be using a different order, I did not attempt to figure out what it was. But it wasn't obviously ordered by the IP or name, possibly by the most recently added interface.

**Comment by MusicDin** [comment] 2024-04-10 09:55
Hi,

IP selection seems to cause troubles over and over again. Currently, we support `user.access_interface` option which can be set in the instance's configuration and will be used to populate `ipv4_address`, `ipv6_address`, and `mac_address` for the *given interface* (example in [Instance Network Access](https://registry.terraform.io/providers/terraform-lxd/lxd/latest/docs/resources/instance#instance-network-access) in docs).

In case `user.access_interface` is not set, the last IP is selected, but looking into the code right now, this does not make a lot of sense, since we are not preordering the retrieved addresses neither by the interface name nor by the IP addresses (need to check, but this seems to me like a regression).

Another issue with IP selection is that if one interface has an IPv4 address set, but IPv6 is not, we try to detect IPv6 from another interface, which can be super confusing. In my opinion, no IPv6 should be reported in such case (this is only applicable when `user.access_interface` is not configured).

Finally, as you have already pointed out, there is currently no way to retrieve information about multiple interfaces. This issue, however, has previously surfaced and is planned to be fixed in the near future (some discussion around that can be found in https://github.com/terraform-lxd/terraform-provider-lxd/pull/427).

---

I think it would be best to (re)introduce deterministic selection of reported addresses either by ordering interfaces by name or their IP values (maybe prioritize IPv4 and if no interface has it, then order by IPv6). 

In addition, we should ensure that all reported addresses are always related to a single interface.

**Comment by tomponline** [comment] 2024-04-10 10:09
Would it be possible/valuable to access/set IPs by interface name or MAC address?

**Comment by tomponline** [comment] 2024-04-10 10:21
One thing to keep in mind is that the device's `name` property for NICs doesn't always match the interface name inside the instance. For containers it normally does, but for VMs it normally doesn't. E.g. if you have a device with a `name` called `eth0` it will likely be `eth0` inside containers, but for VMs it'll likely be `enp5s0`.

So what cloud-init does for matching interfaces is to use the MAC address.

**Comment by MusicDin** [comment] 2024-04-10 10:46
This is a good point. 

The issue I see with MAC addresses is that it would require a user to always set the MAC address for an interface, otherwise it would not be possible to retrieve interface information because MAC is unknown. 

However, with the addition of [Terraform functions (Terraform >= 1.8)](https://developer.hashicorp.com/terraform/plugin/framework/functions/concepts), I think we can provide  a custom function which would accept an instance and MAC address as an argument, and would retrieve the interface matching the given MAC address. This way, the interface list can use interface names as map keys, which are easier to use and create reproducible configurations (despite potential name variations).

**Comment by tomponline** [comment] 2024-04-10 10:55
Yeah this is how cloud init matches lxds device name in config to an actual interface name in the instance

**Closed** 2024-05-24 14:27 UTC
