### ISSUE TITLE
remote not accessible using snap lxd

### ISSUE THREAD

**Issue by pmalhaire** [terraform-lxd/terraform-provider-lxd#145] opened 2018-10-29 11:15 UTC
I have related issue using lxd 3.6 on ubuntu 18.10

The remotes added using lxc are not present using terraform.

I linked the lib using

```
$sudo ln -s /var/snap/lxd/common/lxd /var/lib/lxd
```
as seen in this issue https://github.com/sl1pm4t/terraform-provider-lxd/issues/133

I have a remote named `my_remote`

The following command works :
```
lxc launch my_remote:my_image my_container 
```

But using the provider the following error is given :

could not create image server client: The remote `my_remote` doesn't exist

**Comment by pmalhaire** [comment] 2018-11-11 12:19
I'll, I have nested custom stuff in this tf I need to clean it up.

**Comment by HariBawa** [comment] 2018-11-13 15:56
@pmalhaire @jtopjian 
I have tried link `ln` command and did not work for me. 

Following is workaround code, that I have used to update `main.tf` before terraform run. main.tf is updated based on the lxd installed using snap or apt: 
[main.tf.tmpl](https://github.com/HSBawa/icp-ce-on-linux-containers/blob/master/main.tf.tmpl)
[install.sh](https://github.com/HSBawa/icp-ce-on-linux-containers/blob/master/install.sh)

```
 #############################################
 ## Local (usually default)
   ## Unix Socket Address for
   ##     APT: /var/lib/lxd/unix.socket
   ##    SNAP: /var/snap/lxd/common/lxd/unix.socket
   #############################################
   lxd_remote {
      name     = "local"
      scheme   = "unix"
      address  = "@@UNIX_SOCKET_ADDRESS@@"
      password = ""
    }

```
```
####################################################################################
##  This function is workaround for the terrform plugin snap path issue.
####################################################################################
function select_right_unix_socket_address(){
  local APT_UNIX_SOCKET_ADDRESS="/var/lib/lxd/unix.socket"
  local SNAP_UNIX_SOCKET_ADDRESS="/var/snap/lxd/common/lxd/unix.socket"
  local UNIX_SOCKET_ADDRESS="@@UNIX_SOCKET_ADDRESS@@"
  local lxc_loc="$(which lxc)"

  if [[  -z lxc_loc  ]]; then
     echo "LXC binary not found. Exiting"
     exit;
  fi

  if echo "$lxc_loc" | grep -q "snap"; then
      echo "Updating Socket Address to SNAP"
      sed -i "s|$UNIX_SOCKET_ADDRESS|$SNAP_UNIX_SOCKET_ADDRESS|g" $main_tf
  else
      echo "Updating Socket Address to APT"
      sed -i "s|$UNIX_SOCKET_ADDRESS|$APT_UNIX_SOCKET_ADDRESS|g" $main_tf
  fi

}
```

**Comment by jtopjian** [comment] 2018-11-13 16:22
@HariBawa Isn't this the same as what you reported in #133?

I'm still trying to determine if this issue (#145) is a duplicate of #133 or not.

**Comment by HariBawa** [comment] 2018-11-13 16:30
@jtopjian Yes this is duplicate of #133 . I just posted workaround for pmalhaire , if it helps him in any way as  you update the terraform provider.

**Comment by jtopjian** [comment] 2018-11-13 16:33
@HariBawa OK cool - thank you for clarifying :)

As an aside, I have https://github.com/sl1pm4t/terraform-provider-lxd/pull/147 which should resolve this issue altogether.

**Comment by jtopjian** [comment] 2018-11-15 22:31
Oh! I think I understand the issue here.

@pmalhaire You are adding remotes outside of Terraform and want them to be available in Terraform. Is that correct?

If so, you will still need to define the remote in Terraform. Terraform is unable to detect remotes which are not defined in the `provider` block. It _might_ be possible to add this kind of support. I can't say for sure nor can I give an estimate of how difficult it would be.

I'll leave this issue open as an enhancement.

**Comment by pmalhaire** [comment] 2018-11-20 09:55
@jtopjian It is my need. 
It was working before the the snap version.

I feel sorry I had no time to clarify my problem.

**Comment by jtopjian** [comment] 2018-11-20 21:13
@pmalhaire no problem.

Can you try the latest version and let me know if it now works? If it works with non-snap versions (which is surprising, but I guess it's a feature that is enabled implicitly through some other code), then it might work with the new version.

**Comment by jtopjian** [comment] 2020-12-13 08:18
I'm going to close this issue but I'm happy to re-open it if you're still running into this problem.

**Closed by jtopjian** 2020-12-13 08:18 UTC
Labels: enhancement
