### ISSUE TITLE
Bug: terraform-provider-lxd provider fails to create the instance in the project not equal to "default" if image fingerprint assigned to `image` attribute instead of `image name

### ISSUE THREAD

**Issue by tregubovav-dev** [terraform-lxd/terraform-provider-lxd#489] opened 2024-07-02 19:06 UTC
### Issue

`terraform-provider-lxd` provider fails to create the instance in the project not equal to "default" if image fingerprint assigned to `image` attribute instead of `image name`. Instance creation fails in this case with message like below:
```
lxd_instance.test: Creating...
╷
│ Error: Failed to retrieve image info for instance "test"
│
│   with lxd_instance.test,
│   on install_via_image.tf line 17, in resource "lxd_instance" "test":
│   17: resource "lxd_instance" "test" {
│
│ Image not found
```

### Steps to reproduce

1. create project `test` with default options using command `lxc project create test`
2. deploy infrastructure using terraform or open-tofu using configurations below
 
#### Failed configuration 
```
terraform {
  required_providers {
    lxd = {
      source = "terraform-lxd/lxd"
      version = "2.1.0"
    }
  }
}

resource "lxd_cached_image" "alpine" {
    source_remote       = "images"
    source_image        = "alpine/3.18"
    aliases             = ["alpine-3.18"]
    project             = "test"
}

resource "lxd_instance" "test" {
    name        = "test"
    image       = lxd_cached_image.alpine.fingerprint
    project     = "test"
}
```

#### Working configurations 
```
terraform {
  required_providers {
    lxd = {
      source = "terraform-lxd/lxd"
      version = "2.1.0"
    }
  }
}

resource "lxd_cached_image" "alpine" {
    source_remote       = "images"
    source_image        = "alpine/3.18"
    aliases             = ["alpine-3.18"]
    project             = "default"
}

resource "lxd_instance" "test" {
    name        = "test"
    image       = lxd_cached_image.alpine.fingerprint
    project     = "default"
}
```
**OR**
```
terraform {
  required_providers {
    lxd = {
      source = "terraform-lxd/lxd"
      version = "2.1.0"
    }
  }
}

resource "lxd_cached_image" "alpine" {
    source_remote       = "images"
    source_image        = "alpine/3.18"
    aliases             = ["alpine-3.18"]
}

resource "lxd_instance" "test" {
    name        = "test"
    image       = lxd_cached_image.alpine.fingerprint
}
```

`lxd_cached_image` resource [documentation](https://registry.terraform.io/providers/terraform-lxd/lxd/latest/docs/resources/cached_image) shows how to use 'lxd_instance' with 'lxd_cached_image` resource.  However it does not work with non-"default" project.

I also tried to assign short or long hardcoded 'fingerprint' value of existing image getting by command `lxc image list --project test` with the same result.

[[terraform-provider-incus](https://github.com/lxc/terraform-provider-incus)) has the same [issue](https://github.com/lxc/terraform-provider-incus/issues/94).

**Comment by MusicDin** [comment] 2024-07-02 20:00
Hi, can you share the output of `lxc project show test`?

**Comment by tregubovav-dev** [comment] 2024-07-02 20:51
I forgot to mention that project `test` is project created with default settings. I've updated description.
Project `test` config is below:
```
name: test
description: ""
config:
  features.images: "true"
  features.profiles: "true"
  features.storage.buckets: "true"
  features.storage.volumes: "true"
used_by:
- /1.0/profiles/default?project=test
```

**Comment by tregubovav-dev** [comment] 2024-07-02 21:18
There is one more observation. Resource `lxc_cached_image` does not use attribute `project` from the provider config correctly. See 2 examples below:

### 1. `project` attribute set to `test` in provider's configuration and `project` attribute is undefined in the resources
#### Configuration
```
terraform {
  required_providers {
    lxd = {
      source = "terraform-lxd/lxd"
      version = "2.1.0"
    }
  }
}

provider "lxd" {
    project             = "test"
}
resource "lxd_cached_image" "alpine" {
    source_remote       = "images"
    source_image        = "alpine/3.18"
    aliases             = ["alpine-3.18"]
}

resource "lxd_instance" "test" {
    name        = "test"
    image       = lxd_cached_image.alpine.fingerprint
}
```
#### Applied configuration result
```
lxd_cached_image.alpine: Creating...
lxd_cached_image.alpine: Creation complete after 3s
lxd_instance.test: Creating...

│ Error: Failed to retrieve image info for instance "test"
│
│   with lxd_instance.test,
│   on install_via_image.tf line 21, in resource "lxd_instance" "test":
│   21: resource "lxd_instance" "test" {
│
│ Image not found
```
#### Project `test` after applying configuration
```
name: test
description: ""
config:
  features.images: "true"
  features.profiles: "true"
  features.storage.buckets: "true"
  features.storage.volumes: "true"
used_by:
- /1.0/profiles/default?project=test
```
#### Project `default` after applying configuration
```
name: default
description: Default LXD project
config:
  features.images: "true"
  features.networks: "true"
  features.networks.zones: "true"
  features.profiles: "true"
  features.storage.buckets: "true"
  features.storage.volumes: "true"
used_by:
- /1.0/profiles/default
- /1.0/images/a07acac22a6fcba7593cb258f988a84f96322522071c08f7a1b5dea59f8a5da8
- /1.0/networks/lxdbr0
```
#### Image info `lxc image show a07acac22a6fcba7593cb258f988a84f96322522071c08f7a1b5dea59f8a5da8`
```
auto_update: false
properties:
  architecture: amd64
  description: Alpine 3.18 amd64 (20240702_0017)
  os: Alpine
  release: "3.18"
  requirements.secureboot: "false"
  serial: "20240702_0017"
  type: squashfs
  variant: default
public: false
expires_at: 1970-01-01T00:00:00Z
profiles:
- default
```

### 2. `project` attribute undefined in provider's configuration and set to `test` in the resources
#### Configuration
```
terraform {
  required_providers {
    lxd = {
      source = "terraform-lxd/lxd"
      version = "2.1.0"
    }
  }
}

provider "lxd" {
}
resource "lxd_cached_image" "alpine" {
    source_remote       = "images"
    source_image        = "alpine/3.18"
    aliases             = ["alpine-3.18"]
    project             = "test"
}

resource "lxd_instance" "test" {
    name        = "test"
    image       = lxd_cached_image.alpine.fingerprint
    project     = "test"
}
```

lxd_cached_image.alpine: Creating...
lxd_cached_image.alpine: Creation complete after 4s
lxd_instance.test: Creating...

#### Applied configuration result

│ Error: Failed to retrieve image info for instance "test"
│
│   with lxd_instance.test,
│   on install_via_image.tf line 21, in resource "lxd_instance" "test":
│   21: resource "lxd_instance" "test" {
│
│ Image not found

#### Project `default` after applying configuration
```
name: default
description: Default LXD project
config:
  features.images: "true"
  features.networks: "true"
  features.networks.zones: "true"
  features.profiles: "true"
  features.storage.buckets: "true"
  features.storage.volumes: "true"
used_by:
- /1.0/profiles/default
- /1.0/networks/lxdbr0
```
#### Project `test` after applying configuration
```
name: test
description: ""
config:
  features.images: "true"
  features.profiles: "true"
  features.storage.buckets: "true"
  features.storage.volumes: "true"
used_by:
- /1.0/profiles/default?project=test
- /1.0/images/a07acac22a6fcba7593cb258f988a84f96322522071c08f7a1b5dea59f8a5da8?project=test
```

#### Image info  `lxc image show a07acac22a6fcba7593cb258f988a84f96322522071c08f7a1b5dea59f8a5da8 --project test`
```
auto_update: false
properties:
  architecture: amd64
  description: Alpine 3.18 amd64 (20240702_0017)
  os: Alpine
  release: "3.18"
  requirements.secureboot: "false"
  serial: "20240702_0017"
  type: squashfs
  variant: default
public: false
expires_at: 1970-01-01T00:00:00Z
profiles:
- default
```

**Comment by tregubovav-dev** [comment] 2024-07-02 23:06
Below is a workaround:

Modifying `image` attribute in `lxd_instance` resource from `image = lxd_cached_image.alpine.fingerprint` to `image = format("${lxd_cached_image.alpine.source_remote}:${lxd_cached_image.alpine.fingerprint}")` makes the configuration work.
But, it's still not clear why image remote is required to create instance from cached image.

**Comment by MusicDin** [comment] 2024-07-03 12:42
Thanks, 

I was able to reproduce the issue and will look into fixing it. My assumption is that we are not using a correct image server, which causes the image not to be found.

---

The first approach where `project` is set within a `provider "lxd"` block does not work because there is no such attribute. However, this seems like a validation issue that the unnecessary attribute is allowed.

If there would be an attribute to set the *default project*, it would be linked with a specific remote, not the provider itself.

---

> Modifying image attribute in lxd_instance resource from image = lxd_cached_image.alpine.fingerprint to image = format("${lxd_cached_image.alpine.source_remote}:${lxd_cached_image.alpine.fingerprint}") makes the configuration work.

This is because you are referring to an image by its fingerprint on the `images:` simplestream server, not the local cached image. If image is not found locally, it is transferred from the remote server.

**Comment by MusicDin** [comment] 2024-07-03 12:49
> The first approach where `project` is set within a `provider "lxd"` block does not work because there is no such attribute. However, this seems like a validation issue that the unnecessary attribute is allowed.

I take this one back. It seems the `project` attribute is indeed present in the provider's configuration, but it is not documented. This is another issue we should look at. If it is not used, get rid of it, otherwise ensure it is properly handled (or moved into remote section, as it does not feel right that the project is set for all remotes).

**Comment by tregubovav-dev** [comment] 2024-07-03 13:04
> > The first approach where `project` is set within a `provider "lxd"` block does not work because there is no such attribute. However, this seems like a validation issue that the unnecessary attribute is allowed.
> 
> I take this one back. It seems the `project` attribute is indeed present in the provider's configuration, but it is not documented. This is another issue we should look into. If it is not used, we should get rid of it, otherwise ensure it is properly handled (or moved into remote section, as it does not feel right that the project is set for all remotes).

Hello Din,

At leas this attribute is not documented. However, looking to the [provider.go](https://github.com/terraform-lxd/terraform-provider-lxd/blob/main/internal/provider/provider.go) you can see the corresponded field in the [LxdProviderModel](https://github.com/terraform-lxd/terraform-provider-lxd/blob/4fcee29e520d71e0958173e03c53aa6d6de3287c/internal/provider/provider.go#L42) structure and the [Schema](https://github.com/terraform-lxd/terraform-provider-lxd/blob/4fcee29e520d71e0958173e03c53aa6d6de3287c/internal/provider/provider.go#L87). You probably right, it does not used in the code as
```
			"project": schema.StringAttribute{
				Optional:    true,
				Description: "The project where project-scoped resources will be created. Can be overridden in individual resources. (default = default)",
			},
```

**Closed** 2024-07-04 19:07 UTC
Labels: bug
